build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: "C:\\Python310"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

test_script:
  - "%PYTHON%\\python.exe t/test.py"
